// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type StockPurchase struct {
	ID              uuid.UUID      `json:"id"`
	Symbol          string         `json:"symbol"`
	PriceCents      string         `json:"price_cents"`
	Quantity        int32          `json:"quantity"`
	PurchasedAt     time.Time      `json:"purchased_at"`
	TotalPriceCents string         `json:"total_price_cents"`
	Broker          sql.NullString `json:"broker"`
}

type Task struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Status      sql.NullString `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	Description sql.NullString `json:"description"`
}
