version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_DRIVER: postgres
      DB_STRING: ${DB_STRING}
    ports:
      - "8080:8080"
    volumes:
      - ./modules:/app/modules
      - ./migrations:/app/migrations
    command: >
      sh -c "goose -dir ./migrations postgres \"$DB_STRING\" up &&
             go run modules/main.go"

volumes:
  db_data:
